export type IconName =
  | 'arrowDown'
  | 'arrowUp'
  | 'back'
  | 'calendar'
  | 'chart'
  | 'check'
  | 'clipboard'
  | 'close'
  | 'database'
  | 'document'
  | 'dumbbell'
  | 'edit'
  | 'grid'
  | 'heart'
  | 'help'
  | 'home'
  | 'chevron-right'
  | 'lock'
  | 'preferences'
  | 'trash'
  | 'users'
  | 'tasks'
  // Add any other icon names used in your project here
  | undefined
