export {
  addLog,
  clearLogs,
  createEntry,
  createLogger,
  currentLogLevel,
  formatConsolePretty,
  getLogger,
  getLogs,
  getTime,
  levels,
  logger,
  LoggingService,
  NoLoggingService,
  type ILoggingService,
  type LogEntry,
  type LogLevel,
} from '@gym-pilot/shared'
